global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'kafka-host'
    static_configs:
    - targets: ['192.168.98.101:9100']
    
  - job_name: 'kafka-1'
    static_configs:
    - targets: ['192.168.98.101:9308']